apiVersion: v1
kind: Service
metadata:
  name: m-svc-1
  labels:
    app: m-svc-1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: m-svc-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m-svc-1
  labels:
    app: m-svc-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m-svc-1
  template:
    metadata:
      labels:
        app: m-svc-1
    spec:
      containers:
      - name: m-svc-1-image
        image: m-svc-1-image
        imagePullPolicy: IfNotPresent
        env:
          - name: "spring.config.location"
            value: "/config/"
          - name: "spring.profiles.active"
            value: "local"  
        volumeMounts:
        - name: config-vol
          mountPath: "/config"
          readOnly: true    
      volumes:
      - name: config-vol
        configMap:
          name: m-svc-1-cm
          items:
          - key: "application.yaml"
            path: "application.yaml"
          - key: "application-local.yaml"
            path: "application-local.yaml" 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  m-svc-1-cm
data:
  # spring application configs
  application.yaml: |
    
    spring: 
      application: 
        name: m-svc-1
      webflux:
        base-path: /m-svc-1
    
    server: 
      port: 8080

    management: 
      endpoints: 
        web: 
          exposure: 
            include: "*"
      info:
        git: 
          mode: full

    com:
      sonal:
        skaffold: 
          demo: 
            msvc1:
              greetings:
                message: "Hello"
  
  application-local.yaml: |

    com:  
      sonal:
        skaffold: 
          demo: 
            msvc1:
              greetings:
                message: "Local Hello"
 