apiVersion: v1
kind: ConfigMap
metadata:
  name:  m-svc-1-cm
data:
  {{- $root := . }}
  {{- range .Values.config.files }}
  {{- $curFile := . }}
  {{ $curFile }}: |
  {{- $baseDir := "config/" -}}
  {{- $path :=  print $baseDir $curFile -}}
  {{ $root.Files.Get $path | nindent 4 }}
  {{- end }}